In [1]:
import pandas as pd

In [3]:
pd.read_csv('../datasets/UNEMPLOYMENT RATE 2017.csv', sep = ';', index_col = 0)

                        Unemployment_rate
Country
Afghanistan                          1.56
Albania                             13.75
Algeria                             12.00
Angola                               7.14
Argentina                            8.35
Armenia                             17.83
Australia                            5.59
Austria                              5.50
Azerbaijan                           5.00
Bahamas                             12.38
Bahrain                              0.95
Bangladesh                           4.37
Barbados                             9.49
Belarus                              5.65
Belgium                              7.09
Belize                               9.00
Benin                                2.18
Bhutan                               2.17
Bolivia                              2.17
Bosnia and Herzegovina              20.47
Botswana                            17.63
Brazil                              12.83
Brunei                               9.32
Bulgaria                             6.15
Burkina Faso                         6.01
Burma (Myanmar)                      1.55
Burundi                              1.50
Cambodia                             1.06
Cameroon                             3.36
Canada                               6.34
...                                   ...
Spain                               17.22
Sri Lanka                            4.18
Sudan                               12.77
Suriname                             7.60
Swaziland                           22.34
Sweden                               6.72
Switzerland                          4.80
Syria                                8.03
Tajikistan                          10.74
Tanzania                             1.94
Thailand                             0.63
Togo                                 1.66
Tonga                                1.00
Trinidad and Tobago                  2.82
Tunisia                             15.38
Turkey                              10.82
Turkmenistan                         3.69
Uganda                               1.70
Ukraine                              9.51
United Arab Emirates                 2.46
United Kingdom                       4.34
Uruguay                              7.89
USA                                  4.36
Uzbekistan                           4.97
Vanuatu                              5.42
Venezuela                            7.42
Vietnam                              1.89
Yemen                               13.18
Zambia                               7.21
Zimbabwe                             4.94

[180 rows x 1 columns]